openapi: 3.0.3
info:
  title: MeMaS APIs
  description: |-
    This is the Control Plane and Data Plane APIs for MeMaS (Memory Management Service).
    See https://github.com/memas-ai/MeMaS for more details.
  # termsOfService: http://swagger.io/terms/
  contact:
    email: max.yu@memas.ai
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.1
externalDocs:
  description: Find out more about MeMaS
  url: http://memas.ai
# servers:
#   - url: https://petstore3.swagger.io/api/v3
tags:
  - name: cp
    description: Control Plane APIs for Admins
    # externalDocs:
    #   description: Find out more
    #   url: http://memas.ai
  - name: dp
    description: Data Plane APIs for Chatbots
    # externalDocs:
    #   description: Find out more about our store
    #   url: http://memas.ai
paths:
  /dp/memorize:
    post:
      tags:
        - dp
      summary: Memorize information
      description: Memorize information
      operationId: memorize
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CitedDocument'
                - type: object
                - required:
                    - "corpus_pathname"
                - properties:
                    corpus_pathname:
                      $ref: '#/components/schemas/CorpusPathname'
      responses:
        '200':
          $ref: '#/components/responses/OperationSuccess'
        '400':
          description: Failed operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/NamespaceDoesNotExistError'
                  - $ref: '#/components/schemas/NamespaceIllegalNameError'
      # security:
      #   - petstore_auth:
      #       - write:pets
      #       - read:pets
  /dp/recall:
    get:
      tags:
        - dp
      summary: Recalls information
      description: Recalls relevant information related to the given clue
      operationId: recall
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "clue"
                - "corpus_pathname"
              properties:
                clue:
                  type: string
                  example: "What's the weather?"
                corpus_pathname:
                  $ref: '#/components/schemas/CorpusPathname'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CitedDocument'
        '400':
          description: Failed operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/NamespaceDoesNotExistError'
                  - $ref: '#/components/schemas/NamespaceIllegalNameError'
      # security:
      #   - petstore_auth:
      #       - write:pets
      #       - read:pets
  /cp/user:
    post:
      tags:
        - cp
      summary: Create user
      description: Create a namespace user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "namespace_pathname"
              properties:
                namespace_pathname:
                  $ref: '#/components/schemas/NamespacePathname'
      responses:
        '200':
          $ref: '#/components/responses/OperationSuccess'
        '400':
          description: Failed operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/NamespaceExistError'
                  - $ref: '#/components/schemas/NamespaceIllegalNameError'
    delete:
      tags:
        - cp
      summary: Delete user
      description: Delete a namespace user
      operationId: deleteUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "namespace_pathname"
              properties:
                namespace_pathname:
                  $ref: '#/components/schemas/NamespacePathname'
      responses:
        '200':
          $ref: '#/components/responses/OperationSuccess'
        '400':
          description: Failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespaceDoesNotExistError'
  /cp/corpus:
    post:
      tags:
        - cp
      summary: Create corpus
      description: Create a corpus under a namespace
      operationId: createCorpus
      requestBody:
        # description: Created user object
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "namespace_pathname"
                - "corpus_pathname"
                - "corpus_type"
              properties:
                namespace_pathname:
                  $ref: '#/components/schemas/NamespacePathname'
                corpus_pathname:
                  $ref: '#/components/schemas/CorpusPathname'
                corpus_type:
                  $ref: '#/components/schemas/CorpusType'
      responses:
        '200':
          $ref: '#/components/responses/OperationSuccess'
        '400':
          description: Failed operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/NamespaceExistError'
                  - $ref: '#/components/schemas/NamespaceIllegalNameError'
    delete:
      tags:
        - cp
      summary: Delete corpus
      description: Delete a corpus under a namespace
      operationId: deleteCorpus
      requestBody:
        # description: Deleted user object
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "namespace_pathname"
                - "corpus_pathname"
              properties:
                namespace_pathname:
                  $ref: '#/components/schemas/NamespacePathname'
                corpus_pathname:
                  $ref: '#/components/schemas/CorpusPathname'
      responses:
        '200':
          $ref: '#/components/responses/OperationSuccess'
        '400':
          description: Failed operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NamespaceDoesNotExistError'

components:
  schemas:
    Citation:
      type: object
      properties:
        source_uri:
          type: string
          example: "https://github.com/memas-ai/MeMaS"
        source_name:
          type: string
          example: "github"
        document_name:
          type: string
          example: "MeMaS Readme"
        description:
          type: string
          example: "A Memory Management Service"
    CitedDocument:
      type: object
      required:
        - "document"
        - "citation"
      properties:
        document:
          type: string
          example: |-
            A world has two moons and three suns. And some people love dreaming 
            during daytime.
        citation:
          $ref: '#/components/schemas/Citation'
    CorpusType:
      type: string
      description: Type of a Corpus
      enum:
        - "knowledge"
        - "conversation"
    CorpusPathname:
      type: string
      description: |-
        Full name of a corpus, specifying which namespace the corpus is under. 
        The name takes on the format of \"<namespace_pathname>:<corpus_name>\"
      example: "memas:wikipedia"
    NamespacePathname:
      type: string
      description: |-
        Full namespace name, where child namespaces are appended after their parents'
        names with '.'
      example: "memas.chatbot.persona1"
    NamespaceDoesNotExistError:
      type: object
      description: |-
        Error returned when the namespace object (corpus/user) does not exist
      properties:
        error_code:
          type: string
          enum: ["namespace_does_not_exist"]
        msg:
          type: string
          example: "\"memas:wikipedia\" does not exists, you need to create the resource first"
        details:
          type: string
      required:
        - "error_code"
        - "msg"
    NamespaceExistError:
      type: object
      description: |-
        Error returned when the namespace object (corpus/user) already exists
      properties:
        error_code:
          type: string
          enum: ["namespace_exists"]
        msg:
          type: string
          example: "\"memas:wikipedia\" already exists"
        details:
          type: string
      required:
        - "error_code"
        - "msg"
    NamespaceIllegalNameError:
      type: object
      description: |-
        Error returned when the namespace name format/style is not allowed
      properties:
        error_code:
          type: string
          enum: ["namespace_illegal_name"]
        msg:
          type: string
          example: "\"memas!wikipedia\" is not a valid pathname"
        details:
          type: string
      required:
        - "error_code"
        - "msg"

  responses:
    OperationSuccess:
      description: "Successful Operation"
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
  # securitySchemes:
  #   petstore_auth:
  #     type: oauth2
  #     flows:
  #       implicit:
  #         authorizationUrl: https://petstore3.swagger.io/oauth/authorize
  #         scopes:
  #           write:pets: modify pets in your account
  #           read:pets: read your pets
  #   api_key:
  #     type: apiKey
  #     name: api_key
  #     in: header